version: "3"

services:

  egensign_service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: egensign_service
    network_mode: host
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres

#networks:
#  network1:
#    name: dr
#    external: true
